# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start web development environment
    init: npm install
    command: npm run dev
  - name: Start function development environment
    init: npm install --prefix=apps/functions

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - k--kato.intellij-idea-keybindings
    - PKief.material-icon-theme
    - ms-python.python
    - WallabyJs.quokka-vscode
    - antfu.theme-vitesse
