name: Webhook build
on:
  push:
    branches:
      - 'dev-**'
    paths:
      - '**/webhook-server/**'
  pull_request:
    types: [ labeled ]

jobs:
  do-not-merge:
    runs-on: ubuntu-latest
    steps:
      - name: check labels
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "build"
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: cd apps/webhook-server && npm install
    - name: Run ESLint
      run: cd apps/webhook-server && npm run lint
  push_to_registry:
    needs: lint
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: getviolet/webhook-server
      
      - name: Build  Docker image
        run: cd apps/webhook-server && docker build -t getviolet/webhook-server:latest .
      
      - name: Push image
        run: docker push getviolet/webhook-server:latest
